<x-layouts.public title="FAQ | afacere.online">
    <div class="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
        <section class="max-w-3xl" aria-labelledby="faq-heading"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-zinc-500">FAQ</p><h1 id="faq-heading" class="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Questions entrepreneurs reasonably ask.</h1><p class="mt-5 text-lg text-zinc-600 dark:text-zinc-400">The public site explains the product boundary. Private business state remains behind authentication.</p></section>
        <div class="mt-10 space-y-3">
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">Do I need an account?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">Not to understand the product or pricing. An account is required to save an evaluation and continue into the private business workflow.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">What is the Evaluator?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">It is the entry point into the business progression. It helps establish current context so the product can move toward diagnosis and priorities.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">Can I manage more than one business?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">The application supports configurable business limits through product plans. The active commercial configuration determines what an account can access.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">Does AI make decisions for me?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">No. AI is an assistance layer. Deterministic eligibility and authorization rules remain in application code.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">What are Guides and Opportunities?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">Guides support execution with practical steps. Opportunities surface relevant options when eligibility can be established.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">What are Experts, Marketplace, Community and Events?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">They are ecosystem capabilities connected to the entrepreneur workflow. Personalized discovery belongs in the authenticated business context.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">What about Funding?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">Funding is represented as an Opportunity category. Eligibility and matching remain deterministic and server-side where the workflow supports them.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">What happens to previous evaluations?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">They remain historical versions. A new evaluation does not silently rewrite the old one.</p></details>
            <details class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><summary class="cursor-pointer font-semibold focus-visible:outline-3">Is payment live?</summary><p class="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">Plan presentation follows active application configuration. Production payment processing remains a separate operational concern behind the existing billing boundary.</p></details>
        </div>
    </div>
</x-layouts.public>
