<x-layouts.public title="Legal | afacere.online">
    <div class="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20">
        <section aria-labelledby="legal-heading"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-zinc-500">Legal</p><h1 id="legal-heading" class="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Privacy, terms and responsible product use.</h1><p class="mt-5 text-lg leading-8 text-zinc-600 dark:text-zinc-400">The public site explains the product without exposing private business information. Authenticated workflows remain protected by authentication, business-context authorization and server-side entitlements.</p></section>
        <div class="mt-12 space-y-10">
            <section aria-labelledby="privacy-heading"><h2 id="privacy-heading" class="text-2xl font-semibold">Privacy</h2><p class="mt-3 leading-7 text-zinc-600 dark:text-zinc-400">Only information required to provide the product should be collected and retained. Business information is scoped to authorized users and businesses. Account data can be exported through the authenticated data export workflow, and users can submit a deletion request through their account.</p></section>
            <section aria-labelledby="retention-heading"><h2 id="retention-heading" class="text-2xl font-semibold">Deletion and retention</h2><p class="mt-3 leading-7 text-zinc-600 dark:text-zinc-400">Deletion requests are reviewed before execution. Shared businesses remain available to their other members. Financial and security records may be retained where required for reconciliation, accounting or accountability, with direct user references removed where technically appropriate.</p></section>
            <section aria-labelledby="terms-heading"><h2 id="terms-heading" class="text-2xl font-semibold">Terms</h2><p class="mt-3 leading-7 text-zinc-600 dark:text-zinc-400">afacere.online provides decision-support and execution tooling. Entrepreneurs remain responsible for their business decisions and actions.</p></section>
            <section aria-labelledby="ai-heading"><h2 id="ai-heading" class="text-2xl font-semibold">AI-assisted features</h2><p class="mt-3 leading-7 text-zinc-600 dark:text-zinc-400">AI output is treated as assistance and must not be relied upon as a substitute for professional, legal, financial or other specialist advice. Deterministic authorization and eligibility rules remain server-side.</p></section>
        </div>
        <p class="mt-12 text-sm text-zinc-500 dark:text-zinc-400">Detailed retention and data-lifecycle behavior is documented in the repository. Final production privacy terms remain subject to the appropriate legal review.</p>
    </div>
</x-layouts.public>
